name: Data Extraction Pipeline (PoC)

on:
  push:
    branches: [master]

on:
  workflow_dispatch:

jobs:
  extract-and-load:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment (Python)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests pandas psycopg2-binary

      - name: Jalankan Skrip Uji Coba
        run: python scripts/dummy-pull.py
